apiVersion: v1
data:
    token: ENC[AES256_GCM,data:GCNPa0CNs7daBybL7slH3cF2ouz6oFZ2hpR6IepEFd0XT5NhlBV7/BDPCz+lm4pPiwnhajPZK61hHO0yqUpRcAooZ7MBhiheh4PKueQF74DARTrX355NyvOYkFVSxlq4ttl7otLxABqyIJQ892CupPrHZMsDYUR2MaacRYip/Ha7YL5AacftEVPAWb2CD8AO1VGGPIkE4LqIsI1uqVGtRa6y4vUysbkxtaHazAqP3CrXt7GTFgS70Qt7yh58BmlzYGFDn2OBsEASQIANdTH1++jUbq6py+hmZAv2uMpn/te46Ytubm3Nh0hVNWz5k30woo/L5YH44Z6MH1qpJMoJj7r8pEWP+0szCIBEno7TZdypF9KB5qeYNQENcTH/pacN2ipXPAamptmTSd8F,iv:vaBLW0rW+1qyGBRcVk5ndtBLUv5TNs0+3Wp2bte+9zQ=,tag:Mc4/z1PNwuVhFM9vBYQV+Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gcp-auth-secret
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rjv5qns2ltsmylzvs9mug6njvlc27cc070kw9q3cpd2hekv4jqvq4k6xkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TW9ab2ZTNGFNVmVweTNt
            cFJtU0thb2ZTYTdWU3RyajhpVDgzQndkRUV3ClZVbGxIbkUwWXFoemRkZ2VxZVNX
            RG50L2g1UzZRa3ZlbzFZY0p3MDR3MlEKLS0tIGZHVWdVOVZpRFVVM1BkMVJMRWNn
            QjhmbHJncVQ2TDhvY0M0ZzIwbnJZZUEKB49n7opy4J8poWJCDFKYTC1mqvWc9+6n
            wAr8QJXClm0rWEu28DVQIw8lmyH2jE3jV5/15dYFR5eP60Chx9Rzvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T12:25:15Z"
    mac: ENC[AES256_GCM,data:yDiUnaympCkw3HURc0fDgrKfCxCb7W8agMfPPmaK/3di+nibujebZa10UVdpqI2P6mEj+bGlrltPOt9RQkMpH11t53/MWAW5aGQMC3uC34Ep2J0F8X9eDFcfngkRygENE/NIshIRBzbIjmgMV718QjI/i/JPPU5TSeQ186BAZWA=,iv:ncZLLR5YoKZXZtucX8X26e2rurak7PvB4CeB47biOhg=,tag:0Fu5C//OWoNFHKImyNT97A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
